const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('desktopLyrics', {
  onData: callback => { const listener = (_event, value) => callback(value); ipcRenderer.on('lyrics:data', listener); return () => ipcRenderer.removeListener('lyrics:data', listener); },
  hide: () => ipcRenderer.send('lyrics:hide'),
  showMainWindow: () => ipcRenderer.invoke('lyrics:show-main'),
  command: command => ipcRenderer.send('lyrics:command', command),
  seek: (trackId, seconds) => ipcRenderer.send('lyrics:seek', { trackId, seconds }),
  personalAction: (action, value) => ipcRenderer.invoke('lyrics:personal-action', action, value),
  lockState: () => ipcRenderer.invoke('lyrics:lock-state'),
  hoverState: () => ipcRenderer.invoke('lyrics:hover-state'),
  onHoveredChanged: callback => { const listener = (_event, value) => callback(Boolean(value)); ipcRenderer.on('lyrics:hovered', listener); return () => ipcRenderer.removeListener('lyrics:hovered', listener); },
  pointerGesture: value => ipcRenderer.send('lyrics:pointer-gesture', Boolean(value)),
  bounds: () => ipcRenderer.invoke('lyrics:bounds'),
  resize: size => ipcRenderer.send('lyrics:resize', size),
  setLocked: value => ipcRenderer.invoke('lyrics:set-locked', value),
  getOrientation: () => ipcRenderer.invoke('lyrics:orientation'),
  setOrientation: value => ipcRenderer.invoke('lyrics:set-orientation', value),
  onOrientationChanged: callback => { const listener = (_event, value) => callback(value); ipcRenderer.on('lyrics:orientation', listener); return () => ipcRenderer.removeListener('lyrics:orientation', listener); },
  unlock: () => ipcRenderer.send('lyrics:unlock'),
  onLockedChanged: callback => { const listener = (_event, value) => callback(Boolean(value)); ipcRenderer.on('lyrics:locked', listener); return () => ipcRenderer.removeListener('lyrics:locked', listener); },
});
