const { contextBridge, ipcRenderer } = require('electron');

function subscribe(channel, callback) {
  const listener = (_event, payload) => callback(payload);
  ipcRenderer.on(channel, listener);
  return () => ipcRenderer.removeListener(channel, listener);
}

contextBridge.exposeInMainWorld('yzqxy', {
  updates: { invoke: (args) => ipcRenderer.invoke('updates:invoke', args) },
  desktopLyrics: {
    toggle: () => ipcRenderer.invoke('lyrics:toggle'),
    isVisible: () => ipcRenderer.invoke('lyrics:is-visible'),
    update: (payload) => ipcRenderer.invoke('lyrics:update', payload),
    onVisibleChanged: (callback) => subscribe('lyrics:visible', callback),
  },
  personal: {
    load: () => ipcRenderer.invoke('personal:load'),
    toggle: (kind, track) => ipcRenderer.invoke('personal:toggle', kind, track),
    record: (track) => ipcRenderer.invoke('personal:record', track),
    createPlaylist: (name, firstTrack) => ipcRenderer.invoke('personal:create-playlist', name, firstTrack),
    renamePlaylist: (id, name) => ipcRenderer.invoke('personal:rename-playlist', id, name),
    deletePlaylist: (id) => ipcRenderer.invoke('personal:delete-playlist', id),
    addToPlaylist: (id, track) => ipcRenderer.invoke('personal:add-to-playlist', id, track),
    removeFromPlaylist: (id, trackId) => ipcRenderer.invoke('personal:remove-from-playlist', id, trackId),
    removeSaved: (kind, id) => ipcRenderer.invoke('personal:remove-saved', kind, id),
    onChanged: (callback) => subscribe('personal:changed', callback),
  },
  appearance: {
    load: () => ipcRenderer.invoke('appearance:load'),
    choose: () => ipcRenderer.invoke('appearance:choose'),
    complete: () => ipcRenderer.invoke('appearance:complete'),
    clear: () => ipcRenderer.invoke('appearance:clear'),
    onChanged: (callback) => subscribe('appearance:changed', callback),
  },
  sources: {
    list: () => ipcRenderer.invoke('sources:list'),
      importFile: () => ipcRenderer.invoke('sources:import-file'),
      importFolder: () => ipcRenderer.invoke('sources:import-folder'),
      importUrl: (url) => ipcRenderer.invoke('sources:import-url', url),
      importText: (text, originUrl) => ipcRenderer.invoke('sources:import-text', text, originUrl),
      confirmImport: (token, policy) => ipcRenderer.invoke('sources:confirm-import', token, policy),
      cancelImport: (token) => ipcRenderer.invoke('sources:cancel-import', token),
    setEnabled: (id, enabled) => ipcRenderer.invoke('sources:set-enabled', id, enabled),
    configure: (id, values) => ipcRenderer.invoke('sources:configure', id, values),
    getSettings: (id) => ipcRenderer.invoke('sources:get-settings', id),
    remove: (id) => ipcRenderer.invoke('sources:remove', id),
    search: (id, keyword, cursor, pageSize, requestId) => ipcRenderer.invoke('sources:search', id, keyword, cursor, pageSize, requestId),
    cancelRequest: (requestId) => ipcRenderer.invoke('sources:cancel-request', requestId),
    cached: (track, quality) => ipcRenderer.invoke('sources:cached', track, quality),
    cachedBest: (track, qualities) => ipcRenderer.invoke('sources:cached-best', track, qualities),
    resolve: (track, quality, cacheAsId, skipCache, requestId) => ipcRenderer.invoke('sources:resolve', track, quality, cacheAsId, skipCache, requestId),
      lyrics: (track) => ipcRenderer.invoke('sources:lyrics', track),
      openFolder: () => ipcRenderer.invoke('sources:open-folder'),
    onChanged: (callback) => subscribe('sources:changed', callback),
  },
  cache: {
    stats: () => ipcRenderer.invoke('cache:stats'),
    configure: (options) => ipcRenderer.invoke('cache:configure', options),
    clear: () => ipcRenderer.invoke('cache:clear'),
  },
  library: {
    load: () => ipcRenderer.invoke('library:load'),
    importFolder: () => ipcRenderer.invoke('library:import-folder'),
    addFiles: () => ipcRenderer.invoke('library:add-files'),
    rescan: () => ipcRenderer.invoke('library:rescan'),
    removeRoot: (path) => ipcRenderer.invoke('library:remove-root', path),
    removeFile: (path) => ipcRenderer.invoke('library:remove-file', path),
    readLyrics: (trackId) => ipcRenderer.invoke('library:read-lyrics', trackId),
    createPlaylist: (name) => ipcRenderer.invoke('library:create-playlist', name),
    renamePlaylist: (id, name) => ipcRenderer.invoke('library:rename-playlist', id, name),
    deletePlaylist: (id) => ipcRenderer.invoke('library:delete-playlist', id),
    setPlaylistTracks: (id, trackIds) => ipcRenderer.invoke('library:set-playlist-tracks', id, trackIds),
    importPlaylist: () => ipcRenderer.invoke('library:import-playlist'),
    exportPlaylist: (id) => ipcRenderer.invoke('library:export-playlist', id),
    onChanged: (callback) => subscribe('library:changed', callback),
    onProgress: (callback) => subscribe('library:progress', callback),
  },
  window: {
    minimize: () => ipcRenderer.invoke('window:minimize'),
    toggleMaximize: () => ipcRenderer.invoke('window:toggle-maximize'),
    isMaximized: () => ipcRenderer.invoke('window:is-maximized'),
    toggleFullscreen: () => ipcRenderer.invoke('window:toggle-fullscreen'),
    isFullscreen: () => ipcRenderer.invoke('window:is-fullscreen'),
    onFullscreenChanged: (callback) => subscribe('window:fullscreen-changed', callback),
    close: () => ipcRenderer.invoke('window:close'),
    onMaximizedChanged: (callback) => subscribe('window:maximized-changed', callback),
  },
  onMediaCommand: (callback) => subscribe('media:command', callback),
  onMediaSeek: (callback) => subscribe('media:seek', callback),
});
