import { useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { ArrowDownToLine, ArrowUpFromLine, ChartNoAxesCombined, Clock3, Copy, MonitorSmartphone, Radio, Sparkles, X } from 'lucide-react';
import type { PersonalState } from '../core/types';
import './MusicTools.css';

export type ToolInvoke = <T>(args: Record<string, unknown>) => Promise<T>;
export const desktopTool: ToolInvoke = async args => { if(!window.yzqxy?.companion)throw Error('请使用 Zenix 桌面应用打开此功能');return await window.yzqxy.companion.invoke(args) as never; };
type Tab = 'share' | 'stats' | 'timer' | 'widget';
type Transfer = { listening: boolean; addresses: string[]; code?: string; expiresAt?: number; pending?: { token: string; playlists: { name: string; count: number; localCount: number }[] } | null };
export type Stats = { startedAt: number; from: string; to: string; seconds: number; plays: number; uniqueTracks: number; activeDays: number; topTracks: {title:string;artist:string;seconds:number;plays:number}[]; topArtists: {name:string;seconds:number;plays:number}[]; days: {date:string;seconds:number;plays:number}[] };
function day(date:Date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}
function range(period:string){const to=new Date(),from=new Date(to);if(period==='week')from.setDate(from.getDate()-6);else if(period==='month')from.setDate(1);else{from.setMonth(0);from.setDate(1);}return {from:day(from),to:day(to)};}
const duration=(seconds:number)=>seconds>=3600?`${(seconds/3600).toFixed(1)} 小时`:`${Math.floor(seconds/60)} 分钟`;

export function MusicToolsButton({personal,invoke=desktopTool,platform='Windows',initial='share',ids=[]}:{personal?:PersonalState;invoke?:ToolInvoke;platform?:string;initial?:Tab;ids?:string[]}){
  const [open,setOpen]=useState(false);
  return <><button className="zenix-tools-launch" onClick={()=>setOpen(true)}><Sparkles size={16}/>{initial==='share'?'歌单分享与迁移':initial==='stats'?'听歌统计与回忆':initial==='timer'?'睡眠定时器':'桌面音乐组件'}</button>{open&&createPortal(<MusicTools personal={personal} invoke={invoke} platform={platform} initial={initial} initialIds={ids} close={()=>setOpen(false)}/>,document.body)}</>;
}

export default function MusicTools({personal,invoke=desktopTool,platform='Windows',initial='share',initialIds=[],close}:{personal?:PersonalState;invoke?:ToolInvoke;platform?:string;initial?:Tab;initialIds?:string[];close:()=>void}){
  const [tab,setTab]=useState<Tab>(initial),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState(initialIds);
  const [transfer,setTransfer]=useState<Transfer>({listening:false,addresses:[]}),[address,setAddress]=useState(''),[code,setCode]=useState('');
  const [period,setPeriod]=useState('month'),[stats,setStats]=useState<Stats>(),[theme,setTheme]=useState('aurora');
  const [minutes,setMinutes]=useState(30),[endsAt,setEndsAt]=useState(0),[now,setNow]=useState(Date.now()),[size,setSize]=useState('3x3');
  const [timerMode,setTimerMode]=useState('duration'),[stopTime,setStopTime]=useState('');
  const dialog=useRef<HTMLDivElement>(null),request=useRef(0);
  const closeRef=useRef(close);closeRef.current=close;
  const [loadedPersonal,setLoadedPersonal]=useState<PersonalState>();
  const currentPersonal=personal||loadedPersonal;
  const lists=currentPersonal?.playlists||[];
  useEffect(()=>{if(personal||!window.yzqxy?.personal)return;let active=true;void window.yzqxy.personal.load().then(value=>{if(active)setLoadedPersonal(value);}).catch(error=>setMessage(String(error)));const stop=window.yzqxy.personal.onChanged(value=>{if(active)setLoadedPersonal(value);});return()=>{active=false;stop();};},[personal]);
  useEffect(()=>{const previous=document.activeElement as HTMLElement|null;dialog.current?.focus();const key=(event:KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();event.stopImmediatePropagation();closeRef.current();}else if(event.key==='Tab'){const controls=dialog.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),[tabindex="0"]');if(!controls?.length)return;const first=controls[0],last=controls[controls.length-1];if(event.shiftKey&&(document.activeElement===first||document.activeElement===dialog.current)){event.preventDefault();last.focus();}else if(!event.shiftKey&&(document.activeElement===last||document.activeElement===dialog.current)){event.preventDefault();first.focus();}}};window.addEventListener('keydown',key,true);return()=>{window.removeEventListener('keydown',key,true);previous?.focus();};},[]);
  useEffect(()=>{if(!currentPersonal)return;const valid=new Set(lists.map(list=>list.id));setSelected(ids=>ids.filter(id=>valid.has(id)));},[currentPersonal]);
  useEffect(()=>{if(transfer.pending)dialog.current?.querySelector('.tool-incoming')?.scrollIntoView({block:'nearest'});},[transfer.pending?.token]);
  useEffect(()=>{let active=true;const poll=()=>{if(document.hidden)return;void invoke<Transfer>({operation:'lanStatus'}).then(value=>{if(active)setTransfer(value);}).catch(()=>{});void invoke<{endsAt:number}>({operation:'timerState'}).then(value=>{if(active)setEndsAt(value.endsAt);}).catch(()=>{});};poll();const timer=setInterval(()=>{setNow(Date.now());poll();},1000);return()=>{active=false;clearInterval(timer);};},[invoke]);
  useEffect(()=>{if(tab!=='stats')return;let active=true;const version=++request.current;setStats(undefined);void invoke<Stats>({operation:'stats',...range(period)}).then(value=>{if(active&&request.current===version)setStats(value);}).catch(error=>{if(active)setMessage(error instanceof Error?error.message:'统计读取失败');});return()=>{active=false;};},[tab,period,invoke]);
  async function act<T>(args:Record<string,unknown>,success?:string){if(busy)return;setBusy(true);setMessage('');try{const value=await invoke<T>(args);if(success&&value!==false)setMessage(success);return value;}catch(error){setMessage(error instanceof Error?error.message:'操作未完成，请重试');}finally{setBusy(false);}}
  async function transferAction(operation:string){const value=await act<Transfer>({operation,...(operation==='importConfirm'?{token:transfer.pending?.token}:{})},operation==='importConfirm'?'歌单已导入，同名歌单已自动区分。':undefined);if(value&&typeof value==='object')setTransfer(value);}
  async function copy(text:string){try{await navigator.clipboard.writeText(text);setMessage('已复制');}catch{setMessage('请选中下方文字手动复制');}}
  async function timerSet(){let value=minutes;if(timerMode==='time'){if(!/^\d{2}:\d{2}$/.test(stopTime)){setMessage('请选择停止时间');return;}const end=new Date();const [hours,minute]=stopTime.split(':').map(Number);end.setHours(hours,minute,0,0);if(end.getTime()<=Date.now())end.setDate(end.getDate()+1);value=(end.getTime()-Date.now())/60000;}const state=await act<{endsAt:number}>({operation:'timerSet',minutes:value},'定时任务已设置，到期停止播放并保留应用。');if(state)setEndsAt(state.endsAt);}
  async function saveCard(){if(!stats)return;const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1350;const context=canvas.getContext('2d');if(!context)return;drawMemoryCard(context,stats,theme,period);await act({operation:'saveImage',base64:canvas.toDataURL('image/png').split(',')[1]},'音乐回忆卡已保存。');}
  const countdown=Math.max(0,Math.ceil((endsAt-now)/1000));
  return <div className="zenix-tools-backdrop" onClick={event=>{if(event.target===event.currentTarget)close();}}><div className="zenix-tools" ref={dialog} role="dialog" aria-modal="true" aria-label="Zenix 音乐工具" tabIndex={-1}>
    <header><span>ZENIX / YOUR MUSIC</span><button onClick={close} aria-label="关闭音乐工具"><X size={20}/></button></header>
    <nav aria-label="音乐工具分类">{([{id:'share',label:'歌单分享',icon:Radio},{id:'stats',label:'音乐回忆',icon:ChartNoAxesCombined},{id:'timer',label:'睡眠定时',icon:Clock3},{id:'widget',label:'桌面组件',icon:MonitorSmartphone}] as const).map(item=><button key={item.id} aria-pressed={tab===item.id} onClick={()=>{setTab(item.id);setMessage('');}}><item.icon size={17}/>{item.label}</button>)}</nav>
    <div className="zenix-tools-body">
      {tab==='share'&&<><h1>把歌单带到另一片宇宙</h1><p>分享歌曲清单，不包含音频、本机文件路径或音源授权设置。接收方使用自己的音乐源播放。</p>
        <section><div className="tool-heading"><h3>选择要分享的歌单</h3><button onClick={()=>setSelected(selected.length===lists.length?[]:lists.map(list=>list.id))}>{selected.length===lists.length?'取消全选':'全选'}</button></div><div className="tool-playlists">{lists.map(list=><label key={list.id}><input type="checkbox" checked={selected.includes(list.id)} onChange={event=>setSelected(ids=>event.target.checked?[...ids,list.id]:ids.filter(id=>id!==list.id))}/><span>{list.name}</span><small>{list.tracks.length} 首</small></label>)}{!lists.length&&<p>还没有自定义歌单，可以先导入他人的歌单。</p>}</div>
        <div className="tool-actions"><button disabled={busy||!selected.length} onClick={()=>void act({operation:'exportFile',ids:selected},'.zenixlist 歌单文件已导出。')}><ArrowUpFromLine size={16}/>导出歌单文件</button><button disabled={busy||!!transfer.pending} onClick={()=>void transferAction('importFile')}><ArrowDownToLine size={16}/>导入歌单文件</button></div></section>
        <section><h3>局域网直接迁移</h3><p>两端连接同一 Wi-Fi 或局域网。先在接收端开启接收，再在发送端填写接收地址与配对码。</p><div className="tool-actions"><button disabled={busy||!!transfer.pending} onClick={()=>void transferAction(transfer.listening?'lanStop':'lanStart')}>{transfer.listening?'结束接收':'开启接收 / 查看本机 IP'}</button></div>
        {transfer.listening&&<div className="tool-receiver"><strong>接收已开启 · 最长 15 分钟</strong>{transfer.addresses.map(ip=><div key={ip}><code>{ip}</code><button onClick={()=>void copy(ip)} aria-label={`复制接收地址 ${ip}`}><Copy size={15}/></button></div>)}{!transfer.addresses.length&&<p>没有找到局域网 IPv4 地址，请检查 Wi-Fi / 有线网络连接。</p>}<div><code>配对码：{transfer.code}</code><button onClick={()=>void copy(transfer.code||'')} aria-label="复制配对码"><Copy size={15}/></button></div><small>请让接收端 Zenix 保持打开；发送成功或到期后自动关闭接收。</small></div>}
        <label className="tool-field">接收端地址<input value={address} onChange={event=>setAddress(event.target.value)} placeholder="例如 192.168.1.8:49152" autoComplete="off"/></label><label className="tool-field">接收端配对码<input value={code} onChange={event=>setCode(event.target.value)} placeholder="16 位配对码" maxLength={32} autoComplete="off" spellCheck={false}/></label><button className="tool-primary" disabled={busy||!selected.length||!address.trim()||!code.trim()} onClick={()=>void act({operation:'lanSend',ids:selected,address,code},'已送达，请在接收端确认导入。')}>发送所选歌单</button><small>无法连接时检查接收状态、IP:端口、Windows 防火墙和路由器客户端隔离。</small></section>
        {transfer.pending&&<section className="tool-incoming"><h3>待确认导入</h3>{transfer.pending.playlists.map((list,i)=><div key={i}><strong>{list.name}</strong><span>{list.count} 首{list.localCount>0?` · ${list.localCount} 首本地歌曲需要本机曲库匹配`:''}</span></div>)}<p>会创建独立歌单，同名自动加后缀。音源未配置时可以先保存清单。</p><div className="tool-actions"><button disabled={busy} onClick={()=>void transferAction('importConfirm')}>确认导入</button><button disabled={busy} onClick={()=>void transferAction('importDiscard')}>放弃</button></div></section>}
      </>}
      {tab==='stats'&&<><div className="tool-heading"><h1>你的音乐回忆</h1><select aria-label="统计周期" value={period} onChange={event=>setPeriod(event.target.value)}><option value="week">最近 7 天</option><option value="month">本月</option><option value="year">今年</option></select></div><p>只记录实际播放时间。听满 30 秒或短曲一半计作一次有效播放；保留最近 366 天。</p>{stats?<><div className={`memory-card theme-${theme}`}><span>ZENIX / MUSIC MEMORIES</span><h2>{period==='week'?'这一周的旋律':period==='month'?'这个月，音乐陪着你':'这一年的音乐足迹'}</h2><p>{stats.from} — {stats.to}</p><strong>{duration(stats.seconds)}</strong><div className="memory-metrics"><span>{stats.plays}<small>有效播放</small></span><span>{stats.uniqueTracks}<small>聆听歌曲</small></span><span>{stats.activeDays}<small>有音乐的日子</small></span></div><div className="memory-favorite"><small>陪伴最多的歌</small><b>{stats.topTracks[0]?.title||'等待你的第一段旋律'}</b><span>{stats.topTracks[0]?.artist||'你的音乐，自成宇宙。'}</span></div><i>YOUR MUSIC, YOUR UNIVERSE.</i></div><div className="tool-actions"><select aria-label="回忆卡风格" value={theme} onChange={event=>setTheme(event.target.value)}><option value="aurora">极光玻璃</option><option value="gold">暖金名片</option><option value="midnight">深夜宇宙</option></select><button disabled={busy} onClick={()=>void saveCard()}><ArrowDownToLine size={16}/>保存回忆卡 PNG</button><button onClick={async()=>{const value=await act<Stats>({operation:'stats',...range(period)});if(value)setStats(value);}}>刷新统计</button></div><section><h3>最常听的歌曲</h3>{stats.topTracks.map((track,i)=><div className="tool-rank" key={i}><span>{String(i+1).padStart(2,'0')}</span><div><strong>{track.title}</strong><small>{track.artist||'未知歌手'}</small></div><small>{duration(track.seconds)} · {track.plays} 次</small></div>)}{!stats.topTracks.length&&<p>开始听歌后会逐渐生成回忆；此前的去重历史不会被补算为统计。</p>}</section><section><h3>最常听的歌手</h3>{stats.topArtists.slice(0,5).map((artist,i)=><div className="tool-rank" key={i}><span>{i+1}</span><strong>{artist.name}</strong><small>{duration(artist.seconds)}</small></div>)}</section><section><h3>聆听日历</h3><div className="tool-days">{stats.days.map(value=><span key={value.date} title={`${value.date} · ${duration(value.seconds)}`} style={{opacity:Math.max(.3,Math.min(1,value.seconds/3600))}}>{value.date.slice(5)}<small>{Math.floor(value.seconds/60)}m</small></span>)}</div><small>开始记录：{new Date(stats.startedAt).toLocaleDateString()}</small></section></>:<p role="status">正在读取聆听记录…</p>}</>}
      {tab==='timer'&&<><h1>让音乐陪你慢慢入睡</h1><p>到期停止播放，保留应用、歌单和当前位置。定时任务在播放服务中执行，离开此面板也会继续。</p><section><div className="tool-actions"><button aria-pressed={timerMode==='duration'} onClick={()=>setTimerMode('duration')}>倒计时停止</button><button aria-pressed={timerMode==='time'} onClick={()=>setTimerMode('time')}>指定时间停止</button></div>{timerMode==='duration'?<><div className="tool-actions">{[15,30,60,90].map(value=><button key={value} aria-pressed={minutes===value} onClick={()=>setMinutes(value)}>{value} 分钟</button>)}</div><label className="tool-field">自定义分钟<input type="number" min={1} max={720} value={Number.isFinite(minutes)?minutes:''} onChange={event=>setMinutes(Number(event.target.value))}/></label></>:<label className="tool-field">停止时间（最长 12 小时内）<input type="time" value={stopTime} onChange={event=>setStopTime(event.target.value)}/></label>}<button disabled={busy} className="tool-primary" onClick={()=>void timerSet()}>{countdown?'更新定时任务':'开始定时任务'}</button>{countdown>0&&<div className="tool-countdown"><strong>{String(Math.floor(countdown/3600)).padStart(2,'0')}:{String(Math.floor(countdown/60)%60).padStart(2,'0')}:{String(countdown%60).padStart(2,'0')}</strong><p>预计 {new Date(endsAt).toLocaleTimeString()} 停止播放</p><button disabled={busy} onClick={async()=>{const state=await act<{endsAt:number}>({operation:'timerCancel'},'定时任务已取消。');if(state)setEndsAt(state.endsAt);}}>取消定时任务</button></div>}<small>应用被强制结束后不会自动开始播放；Android 恢复服务时检查已保存的停止时间。</small></section></>}
      {tab==='widget'&&<><h1>桌面上的一小片音乐</h1><p>{platform==='Android'?'将 Zenix 音乐卡放到手机桌面，播放、暂停和切歌都不必打开界面。':'打开独立的 Zenix 音乐小窗，拖动放置并调整大小。'}</p><section><div className="tool-actions">{['3x3','4x2','4x1'].map(value=><button key={value} aria-pressed={size===value} onClick={()=>setSize(value)}>{value.replace('x',' × ')}</button>)}</div><div className={`tool-widget-preview size-${size}`}><span>ZENIX / MUSIC</span>{size==='3x3'&&<div className="tool-widget-disc"/>}<strong>你的音乐，自成宇宙。</strong><small>熟悉的旋律，随手就能听</small><div>Ⅰ◀　　▶　　▶Ⅰ</div></div><button disabled={busy} className="tool-primary" onClick={async()=>{const result=await act<boolean>({operation:platform==='Android'?'widgetPin':'widgetOpen',size});if(result===false)setMessage('桌面不支持直接添加，请长按桌面 → 小组件 → Zenix。');else if(result)setMessage(platform==='Android'?'请在桌面弹出的提示中确认添加。':'音乐小窗已打开。');}}>{platform==='Android'?'添加到桌面':'打开音乐小窗'}</button><small>{platform==='Android'?'可长按组件拉伸调整；实际网格尺寸由桌面启动器决定。':'尺寸代表三种布局比例；Windows 小窗独立于系统小组件面板，主应用需保持运行。'}</small></section></>}
    </div>{message&&<div className="tool-message" role="status">{message}</div>}{busy&&<div className="tool-working" role="status">正在处理…</div>}
  </div></div>;
}

export function drawMemoryCard(ctx:CanvasRenderingContext2D,stats:Stats,theme:string,period:string){
  const palette=theme==='gold'?['#6d5034','#201b1c','#f0d6a7']:theme==='midnight'?['#263049','#080e1c','#c2d6ff']:['#365469','#17192c','#c4f2e9'];
  const gradient=ctx.createLinearGradient(0,0,1080,1350);gradient.addColorStop(0,palette[0]);gradient.addColorStop(1,palette[1]);ctx.fillStyle=gradient;ctx.fillRect(0,0,1080,1350);
  for(let i=0;i<55;i++){ctx.fillStyle=`rgba(255,255,255,${.12+(i%5)*.04})`;ctx.beginPath();ctx.arc(40+(i*163)%1000,30+(i*227)%1290,i%3+1,0,Math.PI*2);ctx.fill();}
  ctx.fillStyle='#ffffff0e';ctx.strokeStyle='#ffffff45';ctx.lineWidth=2;ctx.beginPath();ctx.roundRect(65,65,950,1220,45);ctx.fill();ctx.stroke();
  const line=(text:string,y:number,size:number,color='#f3f6fc')=>{ctx.fillStyle=color;ctx.font=`${size>=44?'600':'400'} ${size}px "Microsoft YaHei",sans-serif`;ctx.fillText(text,110,y,850);};
  line('ZENIX / MUSIC MEMORIES',150,25,palette[2]);line(period==='week'?'这一周的旋律':period==='month'?'这个月，音乐陪着你':'这一年的音乐足迹',285,57);line(`${stats.from} — ${stats.to}`,350,25,'#b6c3d4');line(duration(stats.seconds),510,108,palette[2]);line('有音乐陪伴的时间',570,27,'#cbd7e4');
  const metrics=[`${stats.plays} 次有效播放`,`${stats.uniqueTracks} 首歌曲`,`${stats.activeDays} 个日子`];metrics.forEach((value,i)=>line(value,665+i*55,32));
  line('陪伴最多的歌',920,25,'#b6c3d4');line(stats.topTracks[0]?.title||'等待你的第一段旋律',995,48);line(stats.topTracks[0]?.artist||'你的音乐，自成宇宙。',1055,29,'#c5cddd');line('YOUR MUSIC, YOUR UNIVERSE.',1210,24,palette[2]);
}
