import { useEffect, useRef, useState } from 'react';
import { Capacitor } from '@capacitor/core';
import { motion } from 'framer-motion';
import { ArrowLeft, ArrowRight, Check, Disc3, FolderOpen, Heart, Home, ImagePlus, ListMusic, LoaderCircle, Music2, Pause, Pencil, Play, Plus, Search, Settings2, SkipForward, Star, Trash2, X } from 'lucide-react';
import type { InstalledSource, SourcePreview, Track } from '../core/types';
import { command, initialSnapshot, isAndroid, observe, type MobileSearchPage, type MobileSnapshot } from './native';
import { FullPlayer, Seek, Art, fileUrl } from './Player';
import './mobile.css';

type Page = 'home' | 'space' | 'sources' | 'settings';
type Modal = 'profile' | 'add' | 'create' | 'lists' | 'welcome' | 'licenses' | null;
export default function MobileApp() {
  const [state, setState] = useState<MobileSnapshot>(initialSnapshot);
  const [page, setPage] = useState<Page>('home'), [wall, setWall] = useState<Track[]>([]), [label, setLabel] = useState('最近播放');
  const [searchOpen, setSearchOpen] = useState(false), [keyword, setKeyword] = useState(''), [sourceId, setSourceId] = useState('all');
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [more, setMore] = useState<Record<string, string>>({});
  const [toast, setToast] = useState(''), [modal, setModal] = useState<Modal>(null), [adding, setAdding] = useState<Track>();
  const [name, setName] = useState(''), [bio, setBio] = useState(''), [email, setEmail] = useState(''), [editing, setEditing] = useState('');
  const [url, setUrl] = useState(''), [importing, setImporting] = useState(false), [preview, setPreview] = useState<SourcePreview>();
  const [full, setFull] = useState(false), [orbit, setOrbit] = useState(0), [boot, setBoot] = useState(true);
  const query = useRef(0), lastBack = useRef(0), swiped = useRef(false), backdropVideo = useRef<HTMLVideoElement>(null);
  const [collectionId, setCollectionId] = useState('history');
  const [legal, setLegal] = useState('');
  const player = state.playback, track = player.track, personal = state.personal;
  const enabled = state.sources.filter(source => source.enabled);
  const profile = state.profile || { name: 'Zenix', bio: '你的音乐，自成宇宙。' };
  const background = state.appearance?.background;
  useEffect(() => { if (backdropVideo.current) { if (full) backdropVideo.current.pause(); else void backdropVideo.current.play().catch(() => {}); } }, [full, background?.url]);
  useEffect(() => {
    if (page !== 'space') return;
    if (collectionId === 'liked') setWall(personal.liked);
    else if (collectionId === 'favorites') setWall(personal.favorites);
    else if (collectionId === 'queue') setWall(player.queue);
    else if (collectionId.startsWith('list-')) setWall(personal.playlists.find(list => list.id === collectionId)?.tracks || []);
  }, [page, collectionId, personal.liked, personal.favorites, personal.playlists, player.queue]);
  async function act<T = unknown>(action: string, payload: Record<string, unknown> = {}): Promise<T | undefined> {
    try { return await command<T>(action, payload); } catch (e) { setToast(e instanceof Error ? e.message : '操作失败'); }
  }
  useEffect(() => {
    let alive = true, stop: (() => void) | undefined;
    if (!isAndroid) return;
    void observe(snapshot => { if (alive) setState(previous => snapshot.personal ? snapshot as MobileSnapshot : { ...previous, ...snapshot, playback: { ...previous.playback, ...snapshot.playback } }); }).then(handle => { if (!alive) void handle.remove(); else stop = () => { void handle.remove(); }; });
    const timer = setTimeout(() => { void command<MobileSnapshot>('snapshot').then(snapshot => { if (alive) { setState(snapshot); if (!snapshot.appearance?.completed) setModal('welcome'); } }).catch(e => setToast(String(e))); }, 650);
    return () => { alive = false; clearTimeout(timer); stop?.(); };
  }, []);
  useEffect(() => { const timer = setTimeout(() => setBoot(false), 1100); return () => clearTimeout(timer); }, []);
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(''), 4200); return () => clearTimeout(timer); }, [toast]);
  useEffect(() => {
    const back = () => { if (modal) setModal(null); else if (preview) setPreview(undefined); else if (searchOpen) setSearchOpen(false); else if (full) setFull(false); else if (page !== 'home') setPage('home'); else if (Date.now() - lastBack.current < 1800) void act('exit'); else { lastBack.current = Date.now(); setToast('再按一次返回退出界面，音乐继续播放'); } };
    document.addEventListener('zenix-back', back); return () => document.removeEventListener('zenix-back', back);
  }, [modal, preview, searchOpen, full, page]);
  const wallIds = wall.map(song => song.id).join('|');
  useEffect(() => {
    if (page !== 'space' || !isAndroid) return;
    let cancelled = false;
    void (async () => { for (const song of wall.filter(value => !value.coverUrl && value.source === 'custom')) { if (cancelled) break; try { const value = await command<{ url?: string }>('artwork', { track: song }); if (!cancelled && value.url) setWall(previous => previous.map(item => item.id === song.id ? { ...item, coverUrl: value.url } : item)); } catch {} } })();
    return () => { cancelled = true; };
  }, [page, wallIds]);
  function collection(title: string, tracks: Track[], id = '') { query.current++; setCollectionId(id); setBusy(false); setWall(tracks); setLabel(title); setMore({}); setPage('space'); setSearchOpen(false); }
  function enter() { collection('最近播放', personal.history.map(item => item.track), 'history'); }
  async function play(song: Track, tracks = wall) { const queue = tracks.some(item => item.id === song.id) ? tracks : [song]; const snapshot = await act<MobileSnapshot>('play', { tracks: queue, index: queue.findIndex(item => item.id === song.id) }); if (snapshot) setState(snapshot); void act('notifications'); }
  async function search(append = false) {
    if (!keyword.trim()) return; const version = ++query.current;
    setBusy(true); setError(''); setCollectionId('search'); setPage('space'); setLabel(`搜索 · ${keyword.trim()}`); setSearchOpen(false); if (!append) { setWall([]); setMore({}); }
    const candidates = sourceId === 'all' ? enabled : enabled.filter(source => source.id === sourceId);
    const seen = new Set<string>(); const sources = candidates.filter(source => { const key = source.kind === 'lx' ? (source as InstalledSource & { settings?: Record<string, string> }).settings?.lxCatalog || Object.keys(source.manifest.lxPlatforms || {})[0] : source.id; if (seen.has(key)) return false; seen.add(key); return !append || Boolean(more[source.id]); });
    const results = await Promise.allSettled(sources.map(source => command<MobileSearchPage>('search', { id: source.id, keyword: keyword.trim(), cursor: append ? more[source.id] : '' })));
    if (version !== query.current) return;
    const songs: Track[] = [], cursors: Record<string, string> = {}; const errors: string[] = [];
    results.forEach((result, index) => { if (result.status === 'fulfilled') { songs.push(...result.value.items); if (result.value.nextCursor) cursors[sources[index].id] = result.value.nextCursor; } else errors.push(String(result.reason)); });
    setWall(previous => [...new Map((append ? [...previous, ...songs] : songs).map(song => [song.id, song])).values()]); setMore(cursors); setBusy(false);
    if (!songs.length) setError(candidates.length ? errors[0] || '没有找到匹配歌曲' : '请先配置音乐源，或导入本地音乐');
  }
  const saved = (operation: string, payload: Record<string, unknown>) => void act('personal', { operation, ...payload });
  function add(song: Track) { setAdding(song); setModal('add'); }
  function newList(song?: Track) { setAdding(song); setEditing(''); setName(''); setModal('create'); }
  function actions(song: Track) { return <div className="track-actions">{(['liked', 'favorites'] as const).map(kind => { const selected = personal[kind].some(item => item.id === song.id), Icon = kind === 'liked' ? Heart : Star; return <button key={kind} aria-label={kind === 'liked' ? '喜欢' : '收藏'} aria-pressed={selected} className={selected ? kind : ''} onClick={() => saved('toggle', { kind, track: song })}><Icon fill={selected ? 'currentColor' : 'none'} /></button>; })}<button aria-label="加入歌单" onClick={() => add(song)}><ListMusic /></button></div>; }
  async function importSource(kind: 'importUrl' | 'pickSource') { setImporting(true); const value = await act<SourcePreview>(kind, kind === 'importUrl' ? { url: url.trim() } : {}); if (value) setPreview(value); setImporting(false); }
  const cards = [{ title: '我的喜欢', icon: Heart, songs: personal.liked }, { title: '我的收藏', icon: Star, songs: personal.favorites }, { title: '听歌历史', icon: Disc3, songs: personal.history.map(item => item.track) }, { title: '我的歌单', icon: ListMusic, songs: personal.playlists[0]?.tracks || [] }, { title: '本地曲库', icon: FolderOpen, songs: state.localTracks || [] }, { title: '播放器设置', icon: Settings2, songs: [] }];
  function openCard(index: number) { if(swiped.current){swiped.current=false;return;}if (index === 5) setPage('settings'); else if (index === 3) setModal('lists'); else collection(cards[index].title, cards[index].songs, ['liked','favorites','history','','local'][index]); }
  return <div className={`zenix-mobile page-${page}`}>
    <div className="mobile-backdrop" aria-hidden="true">{background ? background.kind === 'video' ? <video ref={backdropVideo} src={fileUrl(background.url)} muted loop autoPlay playsInline /> : <img src={fileUrl(background.url)} alt="" /> : <div className="default-universe" />}</div>
    <header className="mobile-header"><button className="brand" onClick={() => setPage('home')}>Zenix<span>.</span></button><div><button aria-label="搜索歌曲" onClick={() => setSearchOpen(true)}><Search /></button><button aria-label="设置" onClick={() => setPage('settings')}><Settings2 /></button></div></header>
    <main className="mobile-content">
      {page === 'home' && <section className="personal-home"><div className="home-intro"><p>你的音乐，自成宇宙。</p><button className="glass small" onClick={enter}>进入音乐空间<ArrowRight /></button></div>
        <div className="mobile-orbit" onTouchStart={event => { swiped.current = false; event.currentTarget.dataset.start = String(event.touches[0].clientX); }} onTouchEnd={event => { const delta = event.changedTouches[0].clientX - Number(event.currentTarget.dataset.start); if (Math.abs(delta) > 55) { swiped.current = true; setOrbit(value => (value + (delta < 0 ? 1 : 5)) % cards.length); } }}>
          <button className="satellite left glass" onClick={() => openCard((orbit + 5) % cards.length)}><Art track={cards[(orbit + 5) % cards.length].songs[0]} /><span>{cards[(orbit + 5) % cards.length].title}</span></button>
          <motion.button className="gold-card" whileTap={{ scale: .97 }} onClick={() => { if(swiped.current){swiped.current=false;return;} setName(profile.name); setBio(profile.bio); setEmail(profile.email || ''); setModal('profile'); }}>{background?.kind === 'image' && <img src={fileUrl(background.url)} alt="" />}<div className="gold-signature"><span>ZENIX / ANDROID</span><Disc3 size={15} /></div><div className="gold-profile"><small>Music belongs to your universe.</small><h1>{profile.name}</h1><p>{profile.bio}</p>{profile.email && <small>{profile.email}</small>}<span className="edit-label"><Pencil size={12} />编辑个人名片</span></div></motion.button>
          <button className="satellite right glass" onClick={() => openCard(orbit)}><Art track={cards[orbit].songs[0]} /><span>{cards[orbit].title}</span></button>
        </div><div className="orbit-switch"><button aria-label="上一张卡片" onClick={() => setOrbit(value => (value + 5) % cards.length)}><ArrowLeft /></button><button className="glass" onClick={() => openCard(orbit)}>{cards[orbit].title}<ArrowRight /></button><button aria-label="下一张卡片" onClick={() => setOrbit(value => (value + 1) % cards.length)}><ArrowRight /></button></div>
        <div className="home-collections">{cards.slice(0, 4).map((card, index) => <button className="collection-card glass" key={card.title} onClick={() => openCard(index)}><card.icon /><span>{card.title}</span><small>{index === 3 ? `${personal.playlists.length} 个歌单` : `${card.songs.length} 首歌曲`}</small></button>)}</div><section className="home-recent"><h2>最近播放<button onClick={enter}><ArrowRight /></button></h2><div className="recent-strip">{personal.history.slice(0, 12).map(({ track: song }) => <button key={song.id} onClick={() => { enter(); void play(song, personal.history.map(item => item.track)); }}><Art track={song} /><strong>{song.title}</strong><small>{song.artist}</small></button>)}</div>{!personal.history.length && <button className="empty glass" onClick={() => setSearchOpen(true)}><Search />搜索你的第一首音乐</button>}</section></section>}
      {page === 'space' && <section><div className="section-heading"><div><span>YOUR MUSIC SPACE</span><h1>{label}</h1></div><button aria-label="搜索" onClick={() => setSearchOpen(true)}><Search /></button></div><div className="sticker-wall">{wall.map((song, index) => <motion.article layout key={song.id} className={`mobile-sticker size-${index % 5} ${track?.id === song.id ? 'active-sticker' : ''}`} initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }}><button className="sticker-cover" onClick={() => { if (track?.id === song.id) setFull(true); else void play(song); }}><Art track={song} /><span className="sticker-index">{track?.id === song.id ? '正在播放 · ' : ''}{String(index + 1).padStart(2, '0')}</span><div className="sticker-title"><strong>{song.title}</strong><small>{song.artist}</small></div><span className="sticker-play">{track?.id === song.id && player.playing ? <Pause /> : <Play fill="currentColor" />}</span></button>{actions(song)}{(collectionId.startsWith('list-') || collectionId === 'queue') && <button className="sticker-remove" aria-label="从当前列表移除" onClick={() => collectionId === 'queue' ? void act('removeQueue', { id: song.id }) : saved('removeFromPlaylist', { id: collectionId, trackId: song.id })}><X /></button>}</motion.article>)}</div>{busy && <div className="empty"><LoaderCircle className="spin" />正在查找音乐</div>}{!busy && !wall.length && <div className="empty glass"><Music2 /><p>{error || '这里还没有歌曲'}</p><button className="pill" onClick={() => enabled.length ? setSearchOpen(true) : setPage('sources')}>{enabled.length ? '搜索音乐' : '配置音乐源'}</button><button onClick={() => void act('pickLocal')}>导入本地音乐</button></div>}{!busy && Object.keys(more).length > 0 && <button className="pill load-more" onClick={() => void search(true)}>查看更多</button>}</section>}
      {page === 'sources' && <section><div className="section-heading"><div><span>YOUR SOURCES</span><h1>音乐源</h1></div></div><p className="muted">按接入顺序调用，失败时自动尝试后续资源。脚本由你自行配置。</p><form className="source-import glass" onSubmit={event => { event.preventDefault(); void importSource('importUrl'); }}><input type="url" aria-label="音乐源地址" value={url} onChange={event => setUrl(event.target.value)} placeholder="HTTPS 音乐源地址" /><button className="pill" disabled={importing || !url.trim()} type="submit">{importing ? <LoaderCircle className="spin" /> : <Plus />}导入链接</button><button type="button" disabled={importing} onClick={() => void importSource('pickSource')}><FolderOpen />选择 .js / .zenixsource 文件</button></form>{state.sources.map((source, index) => <article key={source.id} className="source-card glass"><div className="source-title"><span>{String(index + 1).padStart(2, '0')}</span><div><h3>{source.manifest.name}</h3><small>v{source.manifest.version} · {Object.values(source.manifest.lxPlatforms || {}).map(platform => platform.name).join(' / ') || '完整源协议'}</small></div><button className={`toggle ${source.enabled ? 'on' : ''}`} aria-label="启用音乐源" aria-pressed={source.enabled} onClick={() => void act('sourceEnable', { id: source.id, enabled: !source.enabled })}><span /></button></div>{source.manifest.settings.map(field => { const values = (source as InstalledSource & { settings?: Record<string, string> }).settings || {}; return <label className="source-setting" key={field.key}>{field.label}{field.type === 'select' ? <select value={values[field.key] || field.default} onChange={event => void act('sourceConfigure', { id: source.id, values: { ...values, [field.key]: event.target.value } })}>{field.options.map(value => <option key={value}>{value}</option>)}</select> : <input defaultValue={values[field.key] || field.default} onBlur={event => void act('sourceConfigure', { id: source.id, values: { ...values, [field.key]: event.target.value } })} />}</label>; })}<button className="source-delete" onClick={() => { if (window.confirm(`移除「${source.manifest.name}」？歌曲与歌单将保留。`)) void act('sourceRemove', { id: source.id }); }}><Trash2 size={15} />移除</button></article>)}{!state.sources.length && <div className="empty"><Disc3 /><p>还未配置音乐源</p><small>支持兼容脚本及 Zenix 完整源包</small></div>}</section>}
      {page === 'settings' && <section><div className="section-heading"><h1>播放器设置</h1></div><div className="settings-card glass"><h3>个性背景</h3><p>{background?.name || '默认背景'}</p><button className="pill" onClick={() => void act('pickBackground')}><ImagePlus />选择图片或视频</button>{background && <button onClick={() => void act('clearBackground')}>恢复默认背景</button>}</div><div className="settings-card glass"><h3>音乐与缓存</h3><button onClick={() => setPage('sources')}><Settings2 />管理音乐源<ArrowRight /></button><label>播放品质<select defaultValue="high" onChange={event => void act('mode', { quality: event.target.value })}><option value="high">优先高品质，自动降级</option><option value="lossless">优先无损，自动降级</option></select></label><label>自动缓存<button className={`toggle ${state.cache.enabled ? 'on' : ''}`} aria-label="自动缓存" aria-pressed={state.cache.enabled} onClick={() => void act('cacheConfigure', { enabled: !state.cache.enabled })}><span /></button></label><label>缓存上限<select value={state.cache.limitMiB} onChange={event => void act('cacheConfigure', { limitMiB: Number(event.target.value) })}>{[128, 256, 512, 1024, 2048].map(value => <option key={value} value={value}>{value} MiB</option>)}</select></label><p>已用 {(state.cache.usedBytes / 1024 / 1024).toFixed(1)} MiB · 自动清理旧缓存</p><button onClick={() => void act('cacheClear')}><Trash2 />清理缓存</button><button onClick={() => void act('pickLocal')}><FolderOpen />导入本地歌曲作为备用</button></div><div className="settings-card glass"><h3>应用内歌词</h3><label>字体大小<input type="range" min="18" max="38" value={profile.lyricSize || 26} onChange={event => void act('profile', { ...profile, lyricSize: Number(event.target.value) })} /></label><label>歌词颜色<input type="color" value={profile.lyricColor || '#c5e9ff'} onChange={event => void act('profile', { ...profile, lyricColor: event.target.value })} /></label></div><div className="settings-card glass"><h3>Zenix Android</h3><p>0.1.0 · GPL-3.0</p><p>React · Capacitor · Android Media3</p><button onClick={async () => { const text = await act<string>('licenses'); if(text) {setLegal(text);setModal('licenses');} }}>开源许可与致谢<ArrowRight /></button><p>跨应用悬浮歌词将在后续版本接入。</p></div></section>}
    </main>
    {track && !full && <div className="mobile-mini glass"><button className="mini-info" onClick={() => setFull(true)}><Art track={track} /><div><strong>{track.title}</strong><small>{track.artist}</small></div></button><button aria-label={player.playing ? '暂停' : '播放'} onClick={() => void act('toggle')}>{player.playing ? <Pause fill="currentColor" /> : <Play fill="currentColor" />}</button><button aria-label="下一首" onClick={() => void act('next')}><SkipForward /></button><Seek compact position={player.position} duration={player.duration} onSeek={seconds => void act('seek', { seconds })} /></div>}
    <nav className="mobile-nav glass"><button className={page === 'home' ? 'selected' : ''} onClick={() => setPage('home')}><Home />个人</button><button className={page === 'space' ? 'selected' : ''} onClick={enter}><Disc3 />音乐空间</button><button className={page === 'sources' ? 'selected' : ''} onClick={() => setPage('sources')}><Settings2 />音乐源</button></nav>
    {player.sourceActivity && <div className={`mobile-source-status glass phase-${player.sourceActivity.phase}`} role="status">{player.sourceActivity.phase === 'failed' ? <X /> : <LoaderCircle className="spin" />}<span>{player.sourceActivity.message}</span>{player.sourceActivity.phase === 'failed' && <button onClick={() => setPage('sources')}>换源</button>}</div>}
    {searchOpen && <div className="mobile-overlay" onClick={() => setSearchOpen(false)}><section className="mobile-search glass" onClick={event => event.stopPropagation()}><form onSubmit={event => { event.preventDefault(); void search(); }}><Search /><input autoFocus enterKeyHint="search" value={keyword} onChange={event => setKeyword(event.target.value)} placeholder="歌名、歌手，你想听的" /><button aria-label="搜索" type="submit"><ArrowRight /></button><button aria-label="关闭搜索" type="button" onClick={() => setSearchOpen(false)}><X /></button></form><div className="source-chips"><button className={sourceId === 'all' ? 'selected' : ''} onClick={() => setSourceId('all')}>全部音乐</button>{enabled.map(source => <button key={source.id} className={sourceId === source.id ? 'selected' : ''} onClick={() => setSourceId(source.id)}>{source.manifest.name}</button>)}</div>{!enabled.length && <button onClick={() => { setPage('sources'); setSearchOpen(false); }}>先添加自定义音乐源<ArrowRight /></button>}</section></div>}
    {full && track && <FullPlayer state={state} act={act} actions={actions(track)} close={() => setFull(false)} queue={() => { collection('当前队列', player.queue, 'queue'); setFull(false); }} />}
    {(modal || preview) && <div className="mobile-overlay sheet-overlay" onClick={() => { setModal(null); setPreview(undefined); }}><section className="mobile-sheet glass" onClick={event => event.stopPropagation()}><button className="sheet-close" aria-label="关闭" onClick={() => { setModal(null); setPreview(undefined); }}><X /></button>
      {preview && <><h2>确认添加音乐源</h2><h3>{preview.manifest.name}</h3><p>版本 {preview.manifest.version}</p><p className="muted">确认后将运行此脚本，请仅添加可信作者提供的文件。</p><code className="source-hash">SHA256 {preview.sha256}</code><button disabled={importing} className="pill" onClick={async () => { setImporting(true); if (await act('install', { token: preview.token })) { setPreview(undefined); setUrl(''); setToast('音乐源已加入调用队列'); } setImporting(false); }}>{importing ? <LoaderCircle className="spin" /> : <Check />}确认添加</button></>}
      {modal === 'licenses' && <><h2>开源许可与致谢</h2><pre className="mobile-legal">{legal}</pre></>}
      {modal === 'welcome' && <><h2>让这里成为你的音乐空间</h2><p>选择照片或视频作为背景，之后可以在个人空间中修改。</p><button className="pill" onClick={async () => { if (await act('pickBackground')) setModal(null); }}><ImagePlus />选择背景</button><button onClick={() => { void act('completeWelcome'); setModal(null); }}>暂时跳过</button></>}
      {modal === 'profile' && <form onSubmit={event => { event.preventDefault(); void act('profile', { ...profile, name: name.trim() || 'Zenix', bio: bio.trim(), email: email.trim() }); setModal(null); }}><h2>个人名片</h2><label>名字<input value={name} maxLength={30} onChange={event => setName(event.target.value)} /></label><label>签名<textarea value={bio} maxLength={120} onChange={event => setBio(event.target.value)} /></label><label>联系方式<input value={email} maxLength={80} onChange={event => setEmail(event.target.value)} /></label><button type="button" onClick={() => void act('pickBackground')}><ImagePlus />修改照片或视频</button><button className="pill" type="submit"><Check />保存名片</button></form>}
      {modal === 'add' && <><h2>加入歌单</h2>{personal.playlists.map(list => <button key={list.id} className="list-row" onClick={() => { if (adding) saved('addToPlaylist', { id: list.id, track: adding }); setModal(null); }}><Art track={list.tracks[0]} /><span>{list.name}<small>{list.tracks.length} 首</small></span><Plus /></button>)}<button className="pill" onClick={() => newList(adding)}><Plus />新建歌单</button></>}
      {modal === 'create' && <form onSubmit={async event => { event.preventDefault(); if (await act('personal', { operation: editing ? 'renamePlaylist' : 'createPlaylist', id: editing, name, ...(adding ? { track: adding } : {}) })) { setModal('lists'); setAdding(undefined); } }}><h2>{editing ? '重命名歌单' : '新建歌单'}</h2><input autoFocus maxLength={80} value={name} placeholder="给歌单起个名字" onChange={event => setName(event.target.value)} /><button className="pill" disabled={!name.trim()} type="submit"><Check />保存</button></form>}
      {modal === 'lists' && <><h2>我的歌单</h2>{personal.playlists.map(list => <div className="list-row" key={list.id}><button onClick={() => { collection(list.name, list.tracks, list.id); setModal(null); }}><Art track={list.tracks[0]} /><span>{list.name}<small>{list.tracks.length} 首</small></span></button><button aria-label="重命名" onClick={() => { setName(list.name); setEditing(list.id); setAdding(undefined); setModal('create'); }}><Pencil /></button><button aria-label="删除歌单" onClick={() => { if (window.confirm(`删除歌单「${list.name}」？`)) saved('deletePlaylist', { id: list.id }); }}><Trash2 /></button></div>)}<button className="pill" onClick={() => newList()}><Plus />新建歌单</button></>}
    </section></div>}
    {toast && <div className="mobile-toast glass" role="status">{toast}</div>}{!isAndroid && <div className="preview-label">Android 界面预览 · 原生功能需安装 APK</div>}{boot && <motion.div className="mobile-boot" initial={{ opacity: 1 }} animate={{ opacity: 0 }} transition={{ delay: .7, duration: .4 }}><motion.div initial={{ scale: .65, rotate: -20 }} animate={{ scale: 1, rotate: 0 }}><Disc3 size={60} /><h1>Zenix<span>.</span></h1><p>你的音乐，自成宇宙。</p></motion.div></motion.div>}
  </div>;
}
